### ISSUE TITLE
Importing via Jest/Webpack/Babel doesn't work

### ISSUE THREAD

**Issue by mattgibson** [auth0/jwt-decode#64]
I'm using Babel and Webpack, with Jest set up for testing to use Babel too. Both the browser and the specs show this error when I try to use the library:

```
InvalidTokenError
    at Object.<anonymous> (/Users/matthewgibson/code/prodmin/node_modules/jwt-decode/lib/index.js:9:31)
    at Runtime._execModule (/Users/matthewgibson/code/prodmin/node_modules/jest-runtime/build/index.js:448:13)
    at Runtime.requireModule (/Users/matthewgibson/code/prodmin/node_modules/jest-runtime/build/index.js:265:14)
    at Runtime.requireModuleOrMock (/Users/matthewgibson/code/prodmin/node_modules/jest-runtime/build/index.js:337:19)
    at Object.<anonymous> (/Users/matthewgibson/code/prodmin/src/redux/selectors/authenticationSelectors.js:2:18)
```

This is line 2 from `authenticationSelectors.js`: 

```
import jwtDecoder from 'jwt-decode';
```

It seems that Jest is trying to run the function that is assigned to `module.exports` when importing it, rather than just pulling it out as-is. The error is because no arguments are supplied, so the token is `undefined`.

**Comment by mattgibson** [comment]
Ignore me. It's working fine. Babel had messed up my stacktrace and obscured a bug that was causing `undefined` to get passed in from my code.
